package migration

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"
)

// MigrationFunc represents a discovered migration function.
type MigrationFunc struct {
	FileName   string
	FuncName   string
	MigrationName string // e.g. "2026_05_24_000001_create_users_table"
}

// FindMigrations scans for function-based migrations in the style used by the GoW skeleton.
// It looks for functions that take *schema.Builder and are registered in init().
func FindMigrations(dir string) ([]MigrationFunc, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var migrations []MigrationFunc

	// Match function definitions like: func CreateUsersTable(m *schema.Builder) error
	funcRegex := regexp.MustCompile(`func\s+(\w+)\s*\(\s*\w+\s*\*\s*schema\.Builder\s*\)\s*error`)

	// Also try to extract the migration name from the filename
	nameRegex := regexp.MustCompile(`^(\d{4}_\d{2}_\d{2}_\d{6}_.+)(\.go)?$`)

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".go") || name == "register.go" {
			continue
		}

		content, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			continue
		}

		matches := funcRegex.FindAllStringSubmatch(string(content), -1)
		for _, match := range matches {
			if len(match) > 1 {
				funcName := match[1]

				// Derive migration name from filename if possible
				base := strings.TrimSuffix(name, ".go")
				migrationName := base
				if m := nameRegex.FindStringSubmatch(base); len(m) > 1 {
					migrationName = m[1]
				}

				migrations = append(migrations, MigrationFunc{
					FileName:      name,
					FuncName:      funcName,
					MigrationName: migrationName,
				})
			}
		}
	}

	sort.Slice(migrations, func(i, j int) bool {
		return migrations[i].MigrationName < migrations[j].MigrationName
	})

	return migrations, nil
}

// GenerateRegisterFile creates database/migrations/register.go
func GenerateRegisterFile(migrationsDir string, migrations []MigrationFunc) error {
	if len(migrations) == 0 {
		content := `// Code generated by gow. DO NOT EDIT.

package migrations

import "github.com/mechneerd/gow/database/migration"

func init() {
	// No migrations discovered
}
`
		return os.WriteFile(filepath.Join(migrationsDir, "register.go"), []byte(content), 0644)
	}

	tmpl := `// Code generated by gow migrate. DO NOT EDIT.
//
// This file is automatically regenerated.
// Add "database/migrations/register.go" to your .gitignore.

package migrations

import "github.com/mechneerd/gow/database/migration"

func init() {
{{- range . }}
	migration.Register("{{ .MigrationName }}", {{ .FuncName }})
{{- end }}
}
`

	t, err := template.New("register").Parse(tmpl)
	if err != nil {
		return err
	}

	var buf strings.Builder
	if err := t.Execute(&buf, migrations); err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(migrationsDir, "register.go"), []byte(buf.String()), 0644)
}

// EnsureRegisterGoIsGitignored adds the register file to .gitignore
func EnsureRegisterGoIsGitignored(projectRoot string) error {
	gitignorePath := filepath.Join(projectRoot, ".gitignore")
	content, err := os.ReadFile(gitignorePath)
	if err != nil {
		return os.WriteFile(gitignorePath, []byte("database/migrations/register.go\n"), 0644)
	}

	if strings.Contains(string(content), "database/migrations/register.go") {
		return nil
	}

	f, err := os.OpenFile(gitignorePath, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	_, err = f.WriteString("\n# Generated by gow migrate - do not commit\ndatabase/migrations/register.go\n")
	return err
}
