package migration

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"
)

// MigrationFile represents a discovered migration.
type MigrationFile struct {
	FileName  string
	StructName string
}

// FindMigrations scans the given directory for migration files and extracts struct names.
// It looks for .go files (excluding register.go) that define a struct with Up/Down methods.
func FindMigrations(dir string) ([]MigrationFile, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var migrations []MigrationFile

	// Regex to find struct definitions that look like migrations
	structRegex := regexp.MustCompile(`type\s+(\w+)\s+struct`)

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".go") || name == "register.go" {
			continue
		}

		content, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			continue
		}

		matches := structRegex.FindAllStringSubmatch(string(content), -1)
		for _, match := range matches {
			if len(match) > 1 {
				structName := match[1]
				// Heuristic: migration structs usually have "Table" or start with Create/Add
				if strings.Contains(structName, "Table") ||
					strings.HasPrefix(structName, "Create") ||
					strings.HasPrefix(structName, "Add") ||
					strings.HasPrefix(structName, "Modify") {
					migrations = append(migrations, MigrationFile{
						FileName:   name,
						StructName: structName,
					})
				}
			}
		}
	}

	// Sort by filename for consistent order
	sort.Slice(migrations, func(i, j int) bool {
		return migrations[i].FileName < migrations[j].FileName
	})

	return migrations, nil
}

// GenerateRegisterFile creates database/migrations/register.go with init() registrations.
// This file should be gitignored.
func GenerateRegisterFile(migrationsDir string, migrations []MigrationFile) error {
	if len(migrations) == 0 {
		// Still write an empty register file so imports don't break
		content := `// Code generated by gow. DO NOT EDIT.

package migrations

import "github.com/mechneerd/gow/database/migration"

func init() {
	// No migrations found
}
`
		return os.WriteFile(filepath.Join(migrationsDir, "register.go"), []byte(content), 0644)
	}

	tmpl := `// Code generated by gow migrate. DO NOT EDIT.
//
// This file is automatically regenerated before running migrations.
// It is recommended to add "database/migrations/register.go" to your .gitignore.

package migrations

import "github.com/mechneerd/gow/database/migration"

func init() {
{{- range . }}
	migration.Register(&{{ .StructName }}{})
{{- end }}
}
`

	t, err := template.New("register").Parse(tmpl)
	if err != nil {
		return err
	}

	var buf strings.Builder
	if err := t.Execute(&buf, migrations); err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(migrationsDir, "register.go"), []byte(buf.String()), 0644)
}

// EnsureRegisterGoIsGitignored adds register.go to .gitignore if not already present.
func EnsureRegisterGoIsGitignored(projectRoot string) error {
	gitignorePath := filepath.Join(projectRoot, ".gitignore")
	content, err := os.ReadFile(gitignorePath)
	if err != nil {
		// No .gitignore yet — create one
		return os.WriteFile(gitignorePath, []byte("database/migrations/register.go\n"), 0644)
	}

	if strings.Contains(string(content), "database/migrations/register.go") {
		return nil
	}

	// Append
	f, err := os.OpenFile(gitignorePath, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	_, err = f.WriteString("\n# Auto-generated by gow migrate (do not commit)\ndatabase/migrations/register.go\n")
	return err
}
