package artisan

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/joho/godotenv"
	"github.com/spf13/cobra"
)

// ConfigCacheCmd caches the configuration into a Go file for fast loading.
var ConfigCacheCmd = &cobra.Command{
	Use:   "config:cache",
	Short: "Create a cache file for faster configuration loading",
	Run: func(cmd *cobra.Command, args []string) {
		envPath := filepath.Join(".", ".env")
		envMap, err := godotenv.Read(envPath)
		if err != nil {
			fmt.Printf("Error reading .env file: %s\n", err)
			return
		}

		// Also merge current env
		for _, env := range os.Environ() {
			pair := strings.SplitN(env, "=", 2)
			if len(pair) == 2 {
				// Don't overwrite .env variables with empty system ones if not intended,
				// but typically ENV overrides .env. We'll simplify here.
				envMap[pair[0]] = pair[1]
			}
		}

		// Generate config/cached.go
		var sb strings.Builder
		sb.WriteString("// Code generated by artisan config:cache. DO NOT EDIT.\n")
		sb.WriteString("package config\n\n")
		sb.WriteString("var CachedValues = map[string]string{\n")
		for k, v := range envMap {
			sb.WriteString(fmt.Sprintf("\t%q: %q,\n", k, v))
		}
		sb.WriteString("}\n")

		err = os.WriteFile(filepath.Join("config", "cached.go"), []byte(sb.String()), 0644)
		if err != nil {
			fmt.Printf("Error writing cached config: %s\n", err)
			return
		}

		fmt.Println("Configuration cached successfully.")
	},
}

// ConfigClearCmd clears the cached configuration.
var ConfigClearCmd = &cobra.Command{
	Use:   "config:clear",
	Short: "Remove the configuration cache file",
	Run: func(cmd *cobra.Command, args []string) {
		path := filepath.Join("config", "cached.go")
		if _, err := os.Stat(path); err == nil {
			err := os.Remove(path)
			if err != nil {
				fmt.Printf("Error removing cached config: %s\n", err)
				return
			}
		}
		// Create an empty CachedValues so it compiles
		emptyConfig := "// Code generated by artisan config:clear. DO NOT EDIT.\npackage config\n\nvar CachedValues = map[string]string{}\n"
		os.WriteFile(path, []byte(emptyConfig), 0644)
		fmt.Println("Configuration cache cleared.")
	},
}
