package artisan

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/joho/godotenv"
	"github.com/spf13/cobra"
)

// ConfigCacheCmd caches the configuration into a Go file for fast loading.
var ConfigCacheCmd = &cobra.Command{
	Use:   "config:cache",
	Short: "Create a cache file for faster configuration loading",
	Run: func(cmd *cobra.Command, args []string) {
		envPath := filepath.Join(".", ".env")
		envMap, err := godotenv.Read(envPath)
		if err != nil {
			fmt.Printf("Error reading .env file: %s\n", err)
			return
		}

		// Also merge current env
		for _, env := range os.Environ() {
			pair := strings.SplitN(env, "=", 2)
			if len(pair) == 2 {
				// Don't overwrite .env variables with empty system ones if not intended,
				// but typically ENV overrides .env. We'll simplify here.
				envMap[pair[0]] = pair[1]
			}
		}

		// Generate config/cached.go
		var sb strings.Builder
		sb.WriteString("// Code generated by artisan config:cache. DO NOT EDIT.\n")
		sb.WriteString("package config\n\n")
		sb.WriteString("var CachedValues = map[string]string{\n")
		for k, v := range envMap {
			sb.WriteString(fmt.Sprintf("\t%q: %q,\n", k, v))
		}
		sb.WriteString("}\n")

		err = os.WriteFile(filepath.Join("config", "cached.go"), []byte(sb.String()), 0644)
		if err != nil {
			fmt.Printf("Error writing cached config: %s\n", err)
			return
		}

		fmt.Println("Configuration cached successfully.")
	},
}

// ConfigClearCmd clears the cached configuration.
var ConfigClearCmd = &cobra.Command{
	Use:   "config:clear",
	Short: "Clear configuration cache",
	Run: func(cmd *cobra.Command, args []string) {
		cachePath := "bootstrap/cache/config.php" // or .go equivalent in real setup
		if err := os.Remove(cachePath); err == nil {
			fmt.Println("Configuration cache cleared.")
		} else {
			fmt.Println("No configuration cache file found or could not remove it.")
		}
	},
}

